# Generated by Django 3.2.15 on 2022-08-22 18:50

import app.models.base
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=512, null=True, verbose_name='Word or phrase')),
                ('pronunciation', models.CharField(blank=True, max_length=256, null=True, verbose_name='Pronunciation')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
            },
        ),
        migrations.CreateModel(
            name='UserPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_repetition', models.DateField(default=datetime.date.today, verbose_name='Next repetition')),
                ('repeat_schedule', models.JSONField(default=app.models.base.schedule_default)),
                ('in_work', models.BooleanField(default=False)),
                ('base_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase', to='app.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User phrase',
                'verbose_name_plural': 'User phrases',
            },
        ),
    ]
