# Generated by Django 3.2.15 on 2022-08-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phrase_userphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='9:00')),
                ('repetition_1', models.IntegerField(default=3600, verbose_name='First repetition')),
                ('repetition_2', models.IntegerField(default=28800, verbose_name='Second repetition')),
                ('repetition_3', models.IntegerField(default=86400, verbose_name='Third repetition')),
                ('repetition_4', models.IntegerField(default=259200, verbose_name='Fourth repetition')),
                ('repetition_5', models.IntegerField(default=604800, verbose_name='Fifth repetition')),
                ('repetition_6', models.IntegerField(default=1814400, verbose_name='Sixth repetition')),
                ('repetition_7', models.IntegerField(default=7776000, verbose_name='Seventh repetition')),
                ('repetition_8', models.IntegerField(default=15552000, verbose_name='Eighth repetition')),
                ('repetition_9', models.IntegerField(default=31104000, verbose_name='Ninth repetition')),
            ],
            options={
                'verbose_name': 'User schedule',
                'verbose_name_plural': 'User schedules',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule', to='app.userschedule', verbose_name='UserSchedule'),
        ),
    ]
