# Generated by Django 3.2.15 on 2022-09-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userphrase_next_repetition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatschedule',
            options={'verbose_name': 'Repeat schedule', 'verbose_name_plural': 'Repeat scheduler'},
        ),
    ]
