# Generated by Django 3.2.15 on 2022-08-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='token'),
        ),
    ]
