# Generated by Django 3.2.15 on 2022-08-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_phrase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='app.user'),
        ),
    ]
