# Generated by Django 3.2.15 on 2022-08-30 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_create_token',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date create token'),
        ),
    ]
