# Generated by Django 3.2.15 on 2022-09-21 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_user_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.userschedule', verbose_name='User Schedule'),
        ),
        migrations.AlterField(
            model_name='userphrase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
