# Generated by Django 3.2.15 on 2022-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_user_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='repetition_6',
            field=models.IntegerField(default=5184000, verbose_name='Seventh repetition'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='repetition_7',
            field=models.IntegerField(default=7776000, verbose_name='Eighth repetition'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='repetition_8',
            field=models.IntegerField(default=15552000, verbose_name='Ninth repetition'),
        ),
    ]
