# Generated by Django 3.2.15 on 2022-08-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_date_create_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
