# Generated by Django 3.2.15 on 2022-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220921_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='send_on_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
