# Generated by Django 3.2.15 on 2022-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_date_create_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='finish_time',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='start_time',
            field=models.TimeField(default='10:00'),
        ),
    ]
