# Generated by Django 3.2.15 on 2022-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userschedule_send_on_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatschedule',
            options={'ordering': ['next_repeat'], 'verbose_name': 'Repeat schedule', 'verbose_name_plural': 'Repeat scheduler'},
        ),
        migrations.AlterField(
            model_name='phrase',
            name='value',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Word or phrase'),
        ),
    ]
